version: '3.1'

services:
  db:  
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=rahasia
      - MYSQL_DATABASE=space_reservation
    restart: unless-stopped
    volumes:
      - ./mysql-data:/var/lib/mysql

  app:
    build: .
    restart: unless-stopped
    volumes:
      - ./resources/default:/etc/nginx/sites-enabled/default
      - ./tedc-sw-interoperability-exam/src:/var/www/html/alif
      - ./UAS-PengelolaTurnamen:/var/www/html/eep
      - ./E-Voting-KPU:/var/www/html/muzib
      - ./UAS_Booking:/var/www/html/fajar
    ports:
      - "80:80"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: unless-stopped
    ports:
     - 9000:80
    volumes:
     - /sessions
