version: '3.1'

services:
  db:  
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=rahasia
      - MYSQL_DATABASE=space_reservation
    restart: unless-stopped
    volumes:
      - ./mysql-data:/var/lib/mysql

  app:
    build: .
    restart: unless-stopped
    volumes:
      - ./tedc-sw-interoperability-exam/src:/var/www/html/alif
    ports:
      - "${PORT:-3008}:80"
    depends_on:
      - db
